name: Sync to S3

on:
  push:
    branches:
      - Prototype  # or branch name that will be production
    paths:
      - 'static/**'  # Only trigger on changes in the static folder

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # replace with your S3 bucket's region

    - name: Sync files to S3
      run: |
        aws s3 sync static/ s3://qe-unster-net-static/static --delete
        
    - name: Invalidate CloudFront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id E37GCUHREM1Y55 --paths "/*" 